<?php

namespace Database\Seeders;

use App\Models\Kelas;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class KelasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $dataKelas = [
            // Sales-related classes (10 entries)
            [
                'id_kategori' => '9d377e04-f20d-4d39-b57c-505a7fbb65b6',
                'title' => 'Basic Sales Strategies',
                'subtitle' => 'Introduction to essential sales tactics.',
                'harga' => 100000,
                'deskripsi' => 'This course covers the fundamental skills needed to be successful in sales.',
                'foto' => 'sales1.jpg',
                'keuntungan' => 'Learn proven sales techniques to increase revenue.',
                'syarat' => 'Basic communication skills required.',
                'instruktur' => 'John Doe',
                'status' => 'publish',
            ],
            [
                'id_kategori' => '9d377e04-f20d-4d39-b57c-505a7fbb65b6',
                'title' => 'Advanced Sales Techniques',
                'subtitle' => 'Mastering the art of closing deals.',
                'harga' => 150000,
                'deskripsi' => 'Gain insights into advanced sales strategies to close high-value deals.',
                'foto' => 'sales2.jpg',
                'keuntungan' => 'Boost your sales performance with advanced techniques.',
                'syarat' => 'Basic sales knowledge.',
                'instruktur' => 'Jane Smith',
                'status' => 'publish',
            ],
            [
                'id_kategori' => '9d377e04-f20d-4d39-b57c-505a7fbb65b6',
                'title' => 'Customer-Centric Selling',
                'subtitle' => 'Focus on customer needs to drive sales.',
                'harga' => 120000,
                'deskripsi' => 'Learn how to put customers first in your sales approach.',
                'foto' => 'sales3.jpg',
                'keuntungan' => 'Increase customer satisfaction and retention.',
                'syarat' => 'Prior sales experience recommended.',
                'instruktur' => 'Alice Johnson',
                'status' => 'publish',
            ],
            [
                'id_kategori' => '9d377e04-f20d-4d39-b57c-505a7fbb65b6',
                'title' => 'Sales and Negotiation Skills',
                'subtitle' => 'Develop strong negotiation tactics.',
                'harga' => 130000,
                'deskripsi' => 'This course focuses on the key negotiation skills for sales success.',
                'foto' => 'sales4.jpg',
                'keuntungan' => 'Close deals with strong negotiation tactics.',
                'syarat' => 'Basic understanding of sales.',
                'instruktur' => 'Robert Brown',
                'status' => 'publish',
            ],
            [
                'id_kategori' => '9d377e04-f20d-4d39-b57c-505a7fbb65b6',
                'title' => 'B2B Sales Mastery',
                'subtitle' => 'Advanced techniques for business-to-business sales.',
                'harga' => 200000,
                'deskripsi' => 'Learn strategies for effective B2B sales engagements.',
                'foto' => 'sales5.jpg',
                'keuntungan' => 'Master B2B sales skills to grow business partnerships.',
                'syarat' => 'Prior B2B experience recommended.',
                'instruktur' => 'Tom White',
                'status' => 'publish',
            ],
            [
                'id_kategori' => '9d377e04-f20d-4d39-b57c-505a7fbb65b6',
                'title' => 'Digital Sales Fundamentals',
                'subtitle' => 'Adapting sales skills for the digital age.',
                'harga' => 90000,
                'deskripsi' => 'Explore the basics of digital sales strategies and tools.',
                'foto' => 'sales6.jpg',
                'keuntungan' => 'Utilize digital platforms to boost sales.',
                'syarat' => 'Basic internet knowledge.',
                'instruktur' => 'Lisa Green',
                'status' => 'publish',
            ],
            [
                'id_kategori' => '9d377e04-f20d-4d39-b57c-505a7fbb65b6',
                'title' => 'Sales Funnel Optimization',
                'subtitle' => 'Improve your sales process.',
                'harga' => 140000,
                'deskripsi' => 'Learn how to optimize each stage of the sales funnel.',
                'foto' => 'sales7.jpg',
                'keuntungan' => 'Streamline sales processes for better results.',
                'syarat' => 'Basic sales funnel knowledge.',
                'instruktur' => 'Mark Black',
                'status' => 'publish',
            ],
            [
                'id_kategori' => '9d377e04-f20d-4d39-b57c-505a7fbb65b6',
                'title' => 'Sales Data Analysis',
                'subtitle' => 'Use data to drive sales decisions.',
                'harga' => 160000,
                'deskripsi' => 'Understand how to analyze sales data for improved outcomes.',
                'foto' => 'sales8.jpg',
                'keuntungan' => 'Make data-driven sales decisions.',
                'syarat' => 'Basic analytics skills.',
                'instruktur' => 'Karen Blue',
                'status' => 'publish',
            ],
            [
                'id_kategori' => '9d377e04-f20d-4d39-b57c-505a7fbb65b6',
                'title' => 'Inside Sales Essentials',
                'subtitle' => 'Skills for remote sales success.',
                'harga' => 110000,
                'deskripsi' => 'Focus on skills essential for inside sales roles.',
                'foto' => 'sales9.jpg',
                'keuntungan' => 'Learn how to succeed in inside sales.',
                'syarat' => 'Phone communication skills required.',
                'instruktur' => 'David Orange',
                'status' => 'publish',
            ],
            [
                'id_kategori' => '9d377e04-f20d-4d39-b57c-505a7fbb65b6',
                'title' => 'Retail Sales Strategies',
                'subtitle' => 'Increase sales in retail environments.',
                'harga' => 80000,
                'deskripsi' => 'Effective sales strategies for retail settings.',
                'foto' => 'sales10.jpg',
                'keuntungan' => 'Improve in-store sales performance.',
                'syarat' => 'No experience required.',
                'instruktur' => 'Emma Red',
                'status' => 'publish',
            ],

            // Marketing-related classes (5 entries)
            [
                'id_kategori' => 'b891a556-7ef9-11ef-bd8f-af050e34ddb7',
                'title' => 'Digital Marketing Basics',
                'subtitle' => 'Introduction to online marketing.',
                'harga' => 90000,
                'deskripsi' => 'Learn essential digital marketing strategies.',
                'foto' => 'marketing1.jpg',
                'keuntungan' => 'Reach customers online effectively.',
                'syarat' => 'No experience required.',
                'instruktur' => 'Olivia Pink',
                'status' => 'publish',
            ],
            [
                'id_kategori' => 'b891a556-7ef9-11ef-bd8f-af050e34ddb7',
                'title' => 'Social Media Marketing',
                'subtitle' => 'Leverage social media platforms for business.',
                'harga' => 95000,
                'deskripsi' => 'Learn to effectively use social media for marketing.',
                'foto' => 'marketing2.jpg',
                'keuntungan' => 'Increase brand visibility and engagement.',
                'syarat' => 'Basic social media knowledge.',
                'instruktur' => 'Peter Purple',
                'status' => 'publish',
            ],
            [
                'id_kategori' => 'b891a556-7ef9-11ef-bd8f-af050e34ddb7',
                'title' => 'Content Marketing Strategies',
                'subtitle' => 'Develop effective content for marketing.',
                'harga' => 120000,
                'deskripsi' => 'Learn how to create content that drives engagement.',
                'foto' => 'marketing3.jpg',
                'keuntungan' => 'Boost audience engagement with compelling content.',
                'syarat' => 'Basic writing skills.',
                'instruktur' => 'Nancy Yellow',
                'status' => 'publish',
            ],
            [
                'id_kategori' => 'b891a556-7ef9-11ef-bd8f-af050e34ddb7',
                'title' => 'SEO Essentials',
                'subtitle' => 'Improve website ranking on search engines.',
                'harga' => 130000,
                'deskripsi' => 'Introduction to search engine optimization techniques.',
                'foto' => 'marketing4.jpg',
                'keuntungan' => 'Drive organic traffic to your website.',
                'syarat' => 'Basic web knowledge.',
                'instruktur' => 'Victor Violet',
                'status' => 'publish',
            ],
            [
                'id_kategori' => 'b891a556-7ef9-11ef-bd8f-af050e34ddb7',
                'title' => 'Email Marketing Mastery',
                'subtitle' => 'Build successful email campaigns.',
                'harga' => 105000,
                'deskripsi' => 'Learn how to craft emails that convert.',
                'foto' => 'marketing5.jpg',
                'keuntungan' => 'Engage with customers directly via email.',
                'syarat' => 'Basic email handling skills.',
                'instruktur' => 'Laura Lime',
                'status' => 'publish',
            ],

            // Finance-related classes (5 entries)
            [
                'id_kategori' => 'c86e3be2-7af1-11ef-adbb-a6ac690af5b0',
                'title' => 'Financial Planning Essentials',
                'subtitle' => 'Plan your finances effectively.',
                'harga' => 100000,
                'deskripsi' => 'Learn personal finance planning fundamentals.',
                'foto' => 'finance1.jpg',
                'keuntungan' => 'Achieve financial stability.',
                'syarat' => 'Basic understanding of finance.',
                'instruktur' => 'Mia Grey',
                'status' => 'publish',
            ],
            [
                'id_kategori' => 'c86e3be2-7af1-11ef-adbb-a6ac690af5b0',
                'title' => 'Investing for Beginners',
                'subtitle' => 'Introduction to investment basics.',
                'harga' => 110000,
                'deskripsi' => 'Learn the basics of investing.',
                'foto' => 'finance2.jpg',
                'keuntungan' => 'Start investing with confidence.',
                'syarat' => 'No experience required.',
                'instruktur' => 'Noah Silver',
                'status' => 'publish',
            ],
            [
                'id_kategori' => 'c86e3be2-7af1-11ef-adbb-a6ac690af5b0',
                'title' => 'Corporate Finance Fundamentals',
                'subtitle' => 'Understand corporate finance principles.',
                'harga' => 150000,
                'deskripsi' => 'Introduction to corporate finance.',
                'foto' => 'finance3.jpg',
                'keuntungan' => 'Gain insights into corporate finance.',
                'syarat' => 'Basic finance knowledge.',
                'instruktur' => 'Liam Gold',
                'status' => 'publish',
            ],
            [
                'id_kategori' => 'c86e3be2-7af1-11ef-adbb-a6ac690af5b0',
                'title' => 'Budgeting and Forecasting',
                'subtitle' => 'Master budgeting skills.',
                'harga' => 95000,
                'deskripsi' => 'Learn effective budgeting and forecasting.',
                'foto' => 'finance4.jpg',
                'keuntungan' => 'Control expenses and optimize budget.',
                'syarat' => 'No experience required.',
                'instruktur' => 'Emma Bronze',
                'status' => 'publish',
            ],
            [
                'id_kategori' => 'c86e3be2-7af1-11ef-adbb-a6ac690af5b0',
                'title' => 'Financial Analysis and Reporting',
                'subtitle' => 'Learn how to analyze financial data.',
                'harga' => 125000,
                'deskripsi' => 'Gain skills in financial analysis and reporting.',
                'foto' => 'finance5.jpg',
                'keuntungan' => 'Make informed financial decisions.',
                'syarat' => 'Basic finance knowledge.',
                'instruktur' => 'Ava Copper',
                'status' => 'publish',
            ],
        ];

        foreach ($dataKelas as $kelas) {
            Kelas::create($kelas);
        }
    }
}
